### ISSUE TITLE
Schools widget isn't responsive on iOS.

### ISSUE THREAD

**Issue by joshfoskett** [graphiq/real-estate-visualization-api#1]
The schools widget appears to not be (completely) responsive on iOS, and will break out of the container, making the pages width more than it should be. For all other browsers that I've tested, it works as it should.

Chrome on Mac OSX (working as intended):
http://screencast.com/t/5pEV5ldz

Safari on iOS 9.3 (breaks out of container):
http://screencast.com/t/o1ytijjOM

jsbin (with expired token):
http://jsbin.com/jalujatoki/edit?output

**Comment by schnerd** [comment]
Thanks for reporting the issue, Josh. I'll have someone on the team take a look at this.

**Comment by schnerd** [comment]
@joshfoskett I think we finally got a fix out for this, can you give it a try? thanks for your patience.

**Comment by joshfoskett** [comment]
@schnerd Awesome! Seems to be working as expected now.

**Comment by schnerd** [comment]
Excellent!
